create table "public"."todo-lists" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp without time zone not null,
    "todo" text not null,
    "description" text not null
);


alter table "public"."todo-lists" enable row level security;

CREATE UNIQUE INDEX "todo-lists_description_key" ON public."todo-lists" USING btree (description);

CREATE UNIQUE INDEX "todo-lists_pkey" ON public."todo-lists" USING btree (id);

CREATE UNIQUE INDEX "todo-lists_todo_key" ON public."todo-lists" USING btree (todo);

alter table "public"."todo-lists" add constraint "todo-lists_pkey" PRIMARY KEY using index "todo-lists_pkey";

alter table "public"."todo-lists" add constraint "todo-lists_description_key" UNIQUE using index "todo-lists_description_key";

alter table "public"."todo-lists" add constraint "todo-lists_todo_key" UNIQUE using index "todo-lists_todo_key";

grant delete on table "public"."todo-lists" to "anon";

grant insert on table "public"."todo-lists" to "anon";

grant references on table "public"."todo-lists" to "anon";

grant select on table "public"."todo-lists" to "anon";

grant trigger on table "public"."todo-lists" to "anon";

grant truncate on table "public"."todo-lists" to "anon";

grant update on table "public"."todo-lists" to "anon";

grant delete on table "public"."todo-lists" to "authenticated";

grant insert on table "public"."todo-lists" to "authenticated";

grant references on table "public"."todo-lists" to "authenticated";

grant select on table "public"."todo-lists" to "authenticated";

grant trigger on table "public"."todo-lists" to "authenticated";

grant truncate on table "public"."todo-lists" to "authenticated";

grant update on table "public"."todo-lists" to "authenticated";

grant delete on table "public"."todo-lists" to "service_role";

grant insert on table "public"."todo-lists" to "service_role";

grant references on table "public"."todo-lists" to "service_role";

grant select on table "public"."todo-lists" to "service_role";

grant trigger on table "public"."todo-lists" to "service_role";

grant truncate on table "public"."todo-lists" to "service_role";

grant update on table "public"."todo-lists" to "service_role";


